// Generated by Claude
// src/main/antlr4/com/mydynlang/MyDynLang.g4
grammar MyDynLang;

// ─── Parser Rules ───────────────────────────────────────────────────
// (lowercase = parser rules)

program
    : expression EOF
    ;

expression
    : left=atom '+' right=atom
    ;

atom
    : STRING
    ;

// ─── Lexer Rules ────────────────────────────────────────────────────
// (uppercase = lexer rules)

STRING
    : '"' (~["\r\n])* '"'
    ;

// Skip whitespace
WS
    : [ \t\r\n]+ -> skip
    ;